
spring:
  profiles:
    active: dev


# 在 application.yml 中配置
logging:
  level:
    root: info
    com.rbc.boot.log.controller: debug
  file:
    path: ./logs/
  pattern:
    console: '%red(%d{yyyy-MM-dd HH:mm:ss}) %green([%thread]) %highlight(%-5level) %boldMagenta(%logger{10}) - %cyan(%msg%n)'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger : %msg%n'
  logback:
    rolling policy:
      max-file-size: 10MB
      max-history: 10