# 应用服务端口
server:
  port: 8080

# Redis 配置
spring:
  data:
    redis:
      # Redis 服务器地址
      host: 127.0.0.1
      # Redis 服务器连接端口
      port: 6379
      # Redis 数据库索引(默认为 0)
      database: 0
      # Redis 服务器连接密码(默认为空)
      password:
      # 连接超时时间(毫秒)
      timeout: 5000
      lettuce:
        pool:
          # 连接池中的最小空闲连接
          min-idle: 10
          # 连接池中的最大空闲连接
          max-idle: 20
          # 连接池最大连接数(使用负值表示没有限制)
          max-active: 100
          # 连接池最大阻塞等待时间(使用负值表示没有限制)
          max-wait: -1

  # Redis 缓存配置
  cache:
    # 启用缓存
    type: redis
    # 缓存过期时间(秒)
    redis:
      time-to-live: 3600


rbc:
  sms:
    ccp:
      serveIP: app.cloopen.com
      port: 8883
      accountSId: 2c94811c8cd4da0a018f047871856ab5
      accountToken: b84ebec7313344378e8e3f02e7bd6616
      appID: 2c94811c8cd4da0a018f047873166abc
      templateId: 1 # 短信模板ID
